name: blobber_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:

  dart_frog: ^0.3.3
  dart_frog_web_socket: ^0.1.0-dev.3
  protobuf: ^2.1.0
  rxdart: ^0.27.7

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.23.1
  very_good_analysis: ^4.0.0+1
